<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>ui_bridge_node</name>
  <version>0.1.0</version>
  <description>ROS 토픽을 자막 UI 화면에 연결하는 다리 노드</description>
  <maintainer email="meoruu00@gmail.com">JunHyeong Kwon</maintainer>
  <license>MIT</license>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>captioning_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
